language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
  - npm test -- --coverage
  - npm run build
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master